
lidar_node:
  ros__parameters:
    port: '/dev/ttyUSB0'
    baudrate: 230400

ultrasound_node:
  ros__parameters:
    trig_pin1: 23
    echo_pin1: 17
    trig_pin2: 27
    echo_pin2: 22
    trig_pin3: 25
    echo_pin3: 24

control_node:
  ros__parameters:
    kp: 0.4
    s_filter: 0.95
    ang_filter: 0.7
    steering_coef: 0.4
    servo_angle_coef: 0.4
    servo_max: 30
    servo_channel: 0
    esc_channel: 7
    pwm_frequency: 50